name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          # Authenticate using the service account key
          echo "$FIREBASE_TOKEN" > ./service-account.json

          # Deploy to Firebase Hosting
          firebase deploy --token $(cat ./service-account.json) --project=docenclave-d5a43 --only hosting
